import { StyleSheet, Platform } from 'react-native';

export const Colors = {
  primary: '#801919',
  secondary: '#A45D5D',
  cardRed: '#A35D5D',
  cardBorder: '#3A1515',
  background: '#F5F5F5',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#888888',
  text: '#555555',
  placeholder: '#A0A0A0',
  formInputBg: '#F2E3E3',
};

// --- Auth Template Styles ---
export const AuthStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  keyboardView: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  topSection: {
    height: 80,
  },
  archTop: {
    marginHorizontal: 80,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    height: 60,
    zIndex: 1,
  },
  bottomFull: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginTop: -1,
    alignItems: 'center',
  },
  formContent: {
    width: '100%',
    maxWidth: 500,
    paddingHorizontal: 30,
    paddingTop: 10,
    paddingBottom: 40,
    alignSelf: 'center',
  },
});

// --- Layout Utilities ---
export const LayoutStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.white,
    justifyContent: 'space-between',
  },
  scrollContent: {
    padding: 25,
    flexGrow: 1,
    justifyContent: 'center',
  },
  scrollHorizontalContent: {
    flexGrow: 1,
  },
  gridContainer: {
    width: '100%',
  },
  topRow: {
    flexDirection: 'row',
    height: 350,
  },
  rightColumn: {
    flex: 1,
    justifyContent: 'space-between',
  },
  flex1: {
    flex: 1,
  },
  dashboardCardLeft: {
    flex: 1.2,
    marginRight: 15,
  },
  dashboardCardBottom: {
    paddingVertical: 20,
    marginTop: 15,
  },
  textSmall: {
    fontSize: 22,
    marginTop: 5,
  },
  textMedium: {
    fontSize: 22,
  },
  clinicName: {
    color: Colors.white,
    fontSize: 28,
    fontWeight: 'bold',
  },
  clinicAddress: {
    color: Colors.white,
    fontSize: 16,
    opacity: 0.8,
    marginTop: 2,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowEnd: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  mt10: { marginTop: 10 },
  mt15: { marginTop: 15 },
  mt20: { marginTop: 20 },
  mt50: { marginTop: 50 },
  mv10: { marginVertical: 10 },
  mr10: { marginRight: 10 },
  ml10: { marginLeft: 10 },
  ph20: { paddingHorizontal: 20 },
  pt10: { paddingTop: 10 },
  mb40: { marginBottom: 40 },
  w50p: { width: '50%' },
  alignSelfCenter: { alignSelf: 'center' },
  textPlaceholder: { color: Colors.placeholder },
  mt0: { marginTop: 0 },
  mb15: { marginBottom: 15 },
  h50: { height: 50 },
  mh20: { marginHorizontal: 20 },
  tableFixed700: { minWidth: '100%', width: 700 },
  tableFixed1000: { minWidth: '100%', width: 1000 },
  mh25: { marginHorizontal: 25 },
  mh30: { marginHorizontal: 30 },
  ph25: { paddingHorizontal: 25 },
  ph30: { paddingHorizontal: 30 },
  textBold: { fontWeight: 'bold' },
  textPrimary: { color: Colors.primary },
  bgPrimary: { backgroundColor: Colors.primary },
  row: { flexDirection: 'row' },
  mb20: { marginBottom: 20 },
  mb30: { marginBottom: 30 },
});

export const GlobalStyles = StyleSheet.create({
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: Colors.black,
    textAlign: 'center',
  },
  label: {
    fontSize: 14,
    color: Colors.text,
    fontWeight: '500',
  },
  headerContainer: {
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  headerTitle: {
    color: Colors.white,
    fontSize: 22,
    fontWeight: 'bold',
    marginLeft: 15,
  },
  headerRightText: {
    color: Colors.white,
    fontSize: 16,
  },
  topBarContainer: {
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  topBarLogoBadge: {
    backgroundColor: Colors.white,
    width: 55,
    height: 55,
    borderRadius: 27.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  topBarTextRight: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '600',
  },
  topBarTextRightBold: {
    color: Colors.white,
    fontSize: 16,
    marginBottom: 2,
    fontWeight: 'bold',
  },
  alignEnd: {
    alignItems: 'flex-end',
  },
  inputWrapper: {
    marginBottom: 20,
    width: '100%',
  },
  inputLabel: {
    fontSize: 14,
    color: Colors.text,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 25,
    height: 50,
    backgroundColor: Colors.formInputBg,
    paddingHorizontal: 15,
  },
  inputText: {
    flex: 1,
    color: Colors.black,
    fontSize: 16,
  },
  inputIcon: {
    marginRight: 10,
  },
  inputRightIcon: {
    marginLeft: 10,
  },
  pickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F2E3E3',
    borderWidth: 1.5,
    borderColor: Colors.black,
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 55,
  },
  pickerText: {
    fontSize: 16,
    color: Colors.black,
  },
  pickerPlaceholder: {
    color: Colors.placeholder,
  },
  selectionModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectionModalContent: {
    width: '85%',
    backgroundColor: Colors.white,
    borderRadius: 30,
    padding: 25,
    maxHeight: '70%',
    borderWidth: 2,
    borderColor: Colors.black,
  },
  selectionModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    paddingBottom: 15,
  },
  selectionModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  selectionOptionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: '#EEEEEE',
  },
  selectionOptionItemActive: {
    backgroundColor: '#F9F9F9',
  },
  selectionOptionText: {
    fontSize: 16,
    color: '#333',
  },
  selectionOptionTextActive: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  pillInput: {
    borderWidth: 2,
    borderColor: Colors.black,
    borderRadius: 25,
    height: 50,
    backgroundColor: Colors.white,
    color: Colors.black,
    fontSize: 16,
    paddingHorizontal: 20,
  },
  formInput: {
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 25,
    height: 50,
    backgroundColor: Colors.formInputBg,
    color: Colors.black,
    fontSize: 16,
    paddingHorizontal: 20,
  },
  primaryButton: {
    backgroundColor: Colors.primary,
    borderRadius: 25,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  dashboardCard: {
    backgroundColor: Colors.secondary,
    borderWidth: 1.2,
    borderColor: Colors.cardBorder,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  dashboardCardText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 10,
    textAlign: 'center',
  },
  dashboardCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docHeader: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold' as any,
    fontSize: 22,
    textAlign: 'center',
    color: Colors.black,
  },
  docTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold' as any,
    fontSize: 18,
    textAlign: 'center',
    color: Colors.black,
    marginVertical: 10,
  },
  docBodySerif: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontSize: 14,
    color: Colors.black,
  },
  docBodyCursive: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontStyle: 'italic',
    fontSize: 14,
    fontWeight: '600' as any,
    color: Colors.black,
  },
  bottomNavContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    height: 70,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    elevation: 8,
  },
  bottomNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  bottomNavText: {
    color: Colors.white,
    fontSize: 11,
    marginTop: 4,
    opacity: 0.8,
  },
  bottomNavActiveText: {
    opacity: 1,
    fontWeight: 'bold',
  },
  formCard: {
    backgroundColor: Colors.white,
    marginHorizontal: 20,
    borderRadius: 25,
    padding: 30,
    borderWidth: 2,
    borderColor: Colors.black,
    elevation: 3,
  },
  formSectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#333',
    marginBottom: 8,
    letterSpacing: 1.2,
  },
  formDivider: {
    height: 1,
    backgroundColor: Colors.black,
    marginBottom: 20,
    opacity: 0.3,
  },
  btnBatal: {
    backgroundColor: '#B3AFAF',
    width: 140,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  btnBatalText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  btnSimpan: {
    backgroundColor: '#2E50D4',
    width: 140,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  btnActionUpdate: {
    backgroundColor: '#EBC112',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnActionDelete: {
    backgroundColor: Colors.primary,
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    marginRight: 10,
    backgroundColor: 'rgba(255,255,255,0.2)',
    padding: 5,
    borderRadius: 10,
  },
  userCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: Colors.black,
    backgroundColor: Colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EEEEEE',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#E0E0E0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  avatarText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.black,
  },
  userName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.text,
  },
  userRole: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: 20,
    width: '100%',
  },
  detailItem: {
    flex: 1,
    paddingRight: 10,
  },
  detailLabel: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.black,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: 16,
    color: '#666',
    fontStyle: 'italic',
    lineHeight: 22,
  },
  detailFooter: {
    marginTop: 20,
    alignItems: 'flex-end',
  },
  btnBack: {
    backgroundColor: '#2E50D4',
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 20,
  },
  btnBackText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 15,
  },
  listTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
  },
  listSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 15,
    paddingHorizontal: 15,
    borderWidth: 2,
    borderColor: Colors.black,
    height: 60,
    flex: 1,
  },
  listSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  listAddButton: {
    backgroundColor: '#2E50D4',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    height: 60,
    borderRadius: 12,
    justifyContent: 'center',
  },
  listAddButtonText: {
    color: 'white',
    fontWeight: 'bold',
    marginLeft: 5,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 5,
  },
  searchWrapper: {
    flex: 1,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  listAddButtonContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  listLeftSpacer: {
    width: 0,
    display: 'none',
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  emptyContent: {
    alignItems: 'center',
    marginTop: 50,
  },
  emptyText: {
    color: '#888',
    fontSize: 16,
  },
  cardActions: {
    flexDirection: 'row',
  },
  cardActionBtn: {
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalBox: {
    width: '85%',
    backgroundColor: Colors.white,
    borderRadius: 40,
    paddingVertical: 25,
    paddingHorizontal: 25,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.primary,
  },
  modalText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.black,
    textAlign: 'center',
    marginBottom: 20,
  },
  modalActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  btnModalBatal: {
    backgroundColor: '#B3AFAF',
    flex: 1,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  btnModalHapus: {
    backgroundColor: Colors.primary,
    flex: 1,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  btnModalText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  tableContainer: {
    flex: 1,
    marginBottom: 20,
  },
  tableContentWrapper: {
    backgroundColor: Colors.white,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderWidth: 2,
    borderColor: Colors.black,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    borderBottomWidth: 2,
    borderBottomColor: Colors.black,
    width: '100%',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: Colors.black,
    width: '100%',
  },
  tableRowLast: {
    borderBottomWidth: 2,
  },
  tableHeaderCell: {
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
    borderRightColor: Colors.black,
  },
  tableCell: {
    paddingVertical: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
    borderRightColor: Colors.black,
  },
  tableCellNo: {
    width: 50,
  },
  tableCellName: {
    flex: 1,
    paddingHorizontal: 12,
    alignItems: 'flex-start',
  },
  tableCellRole: {
    width: 100,
  },
  tableCellSpec: {
    width: 130,
  },
  tableCellTglLahir: {
    width: 110,
  },
  tableCellJK: {
    width: 110,
  },
  tableCellAlamat: {
    width: 200,
  },
  tableCellPekerjaan: {
    width: 120,
  },
  tableCellNope: {
    width: 120,
  },
  tableCellAlergi: {
    width: 120,
  },
  tableCellDokter: {
    width: 150,
  },

  // Detail View Styles (Read Pasien)
  detailMainCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 50,
    padding: 40,
    marginTop: 30,
    marginHorizontal: 35, // Increased from 25
    // Soft Premium Shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 5,
  },
  // Form Picker Utilities
  // Form Picker Utilities
  btnKembaliLink: {
    backgroundColor: '#2D58D1', // Nicer blue
    paddingVertical: 15,
    paddingHorizontal: 50,
    borderRadius: 35,
  },
  btnKembaliText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
    textTransform: 'none',
  },
  tableCellAction: {
    width: 140,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRightWidth: 0,
  },
  tableHeaderText: {
    fontWeight: 'bold',
    fontSize: 15,
    color: Colors.black,
  },
  tableRowText: {
    fontSize: 14,
    color: Colors.black,
  },
  captchaSection: {
    marginTop: 10,
    marginBottom: 35,
  },
  captchaBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#888888',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  captchaText: {
    marginLeft: 10,
    fontSize: 14,
    color: '#333333',
  },
  captchaHint: {
    fontSize: 10,
    color: Colors.primary,
    marginTop: 8,
    fontStyle: 'italic',
    marginLeft: 4,
  },
  captchaMathBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  captchaMathQuestion: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 8,
    overflow: 'hidden' as any,
    borderWidth: 1,
    borderColor: '#DDDDDD'
  },
  captchaMathInput: {
    borderWidth: 1,
    borderColor: '#888888',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 8,
    fontSize: 16,
    width: 100,
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    color: '#333333'
  },
  cardWrapper: {
    backgroundColor: Colors.cardRed,
    borderRadius: 15,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#984B4B',
  },
  cardVertical: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardText: {
    color: Colors.white,
    fontWeight: 'bold',
    marginTop: 10,
    textAlign: 'center',
  },
  cardTextHorizontal: {
    marginLeft: 15,
    marginTop: 0,
  },
  infoCardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
  },
  infoCardIconContainer: {
    width: 45,
    height: 45,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  infoCardTextContainer: {
    flex: 1,
  },
  infoCardLabel: {
    fontSize: 12,
    color: '#888',
    marginBottom: 2,
  },
  infoCardValue: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  baseCardBody: {
    borderRadius: 15,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#EEE',
  },
});
