import { StyleSheet, Platform } from 'react-native';

export const Colors = {
  primary: '#801919',
  secondary: '#A45D5D',
  cardRed: '#A35D5D',
  cardBorder: '#3A1515',
  background: '#F5F5F5',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#888888',
  text: '#555555',
  placeholder: '#A0A0A0',
  formInputBg: '#F2E3E3',
};


export const AuthStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  keyboardView: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.primary,
  },
  topSection: {
    height: 80,
  },
  archTop: {
    marginHorizontal: 80,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    height: 60,
    zIndex: 1,
  },
  bottomFull: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginTop: -1,
    alignItems: 'center',
  },
  formContent: {
    width: '100%',
    maxWidth: 500,
    paddingHorizontal: 30,
    paddingTop: 10,
    paddingBottom: 40,
    alignSelf: 'center',
  },
  w100p: {
    width: '100%',
  },
});


export const LayoutStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    justifyContent: 'space-between',
  },
  scrollContent: {
    padding: 25,
    flexGrow: 1,
  },
  scrollHorizontalContent: {
    flexGrow: 1,
  },
  gridContainer: {
    width: '100%',
  },
  topRow: {
    flexDirection: 'row',
    height: 350,
  },
  rightColumn: {
    flex: 1,
    justifyContent: 'space-between',
  },
  flex1: {
    flex: 1,
  },
  dashboardCardLeft: {
    flex: 1.2,
    marginRight: 15,
  },
  dashboardCardBottom: {
    paddingVertical: 20,
    marginTop: 15,
  },
  textSmall: {
    fontSize: 22,
    marginTop: 5,
  },
  textMedium: {
    fontSize: 22,
  },
  clinicName: {
    color: Colors.white,
    fontSize: 20,
    fontWeight: 'bold',
  },
  clinicAddress: {
    color: Colors.white,
    fontSize: 11,
    opacity: 0.8,
    marginTop: 1,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowEnd: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },

  mt0: { marginTop: 0 },
  mt5: { marginTop: 5 },
  mt10: { marginTop: 10 },
  mt15: { marginTop: 15 },
  mt20: { marginTop: 20 },
  mt50: { marginTop: 50 },
  mv10: { marginVertical: 10 },
  mr10: { marginRight: 10 },
  mr15: { marginRight: 15 },
  ml10: { marginLeft: 10 },
  ph20: { paddingHorizontal: 20 },
  ph25: { paddingHorizontal: 25 },
  ph30: { paddingHorizontal: 30 },
  pt10: { paddingTop: 10 },
  p20: { padding: 20 },
  pb20: { paddingBottom: 20 },
  mb5: { marginBottom: 5 },
  mb10: { marginBottom: 10 },
  mt30: { marginTop: 30 },
  mb15: { marginBottom: 15 },
  mb20: { marginBottom: 20 },
  mb25: { marginBottom: 25 },
  mb30: { marginBottom: 30 },
  mb40: { marginBottom: 40 },
  mh20: { marginHorizontal: 20 },
  mh25: { marginHorizontal: 25 },
  mh30: { marginHorizontal: 30 },
  h50: { height: 50 },
  h35: { height: 35 },
  w50p: { width: '50%' },
  w50: { width: 50 },
  w60: { width: 60 },
  w70: { width: 70 },
  w80: { width: 80 },
  w90: { width: 90 },
  w100: { width: 100 },
  w130: { width: 130 },
  w140: { width: 140 },
  w150: { width: 150 },
  w160: { width: 160 },
  w170: { width: 170 },
  w180: { width: 180 },
  w200: { width: 200 },
  w220: { width: 220 },
  w250: { width: 250 },
  w270: { width: 270 },
  w280: { width: 280 },
  w300: { width: 300 },
  w700: { width: 700 },
  w900: { width: 900 },
  w1100: { width: 1100 },
  w1160: { width: 1160 },
  minW250: { minWidth: 250 },
  alignSelfCenter: { alignSelf: 'center' },
  textPlaceholder: { color: Colors.placeholder },
  textBold: { fontWeight: 'bold' },
  textPrimary: { color: Colors.primary },
  bgPrimary: { backgroundColor: Colors.primary },
  bgWhite: { backgroundColor: Colors.white },
  tableFixed700: { minWidth: '100%', width: 700 },
  tableFixed1000: { minWidth: '100%', width: 1000 },
  row: { flexDirection: 'row' },
  flexRow: { flexDirection: 'row' },
  flexWrap: { flexWrap: 'wrap' },
  alignCenter: { alignItems: 'center' },
  justifyEnd: { justifyContent: 'flex-end' },
  stretch: { alignItems: 'stretch' },
  shadowCard: {
    elevation: 3,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  italicText: {
    fontStyle: 'italic',
    color: '#555',
  },
  centerText: {
    textAlign: 'center',
  },
  textGray: {
    color: '#888',
  },
  textGrayDark: {
    color: '#555',
  },
  textDark: {
    color: '#333',
  },
  textBoldHuge: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  textSmallPrimary: {
    fontSize: 12,
    color: Colors.primary,
    fontWeight: 'bold',
  },
  textCenterGray: {
    textAlign: 'center',
    marginBottom: 15,
    color: '#666',
  },
  justifyCenter: {
    justifyContent: 'center',
  },
  flex0: {
    flex: 0,
  },
  textJustify: {
    textAlign: 'justify',
  },
  lineHeight22: {
    lineHeight: 22,
  },
  gap15: {
    gap: 15,
  },
  gap8: {
    gap: 8,
  },
  gap20: {
    gap: 20,
  },
  w100p: {
    width: '100%',
  },
  h60: {
    height: 60,
  },
  h100: {
    height: 100,
  },
  mh0: {
    marginHorizontal: 0,
  },
  border0: {
    borderWidth: 0,
    borderBottomWidth: 0,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
  },
  w120: {
    width: 120,
  },
  w1000: {
    width: 1000,
  },
  borderR0: {
    borderRightWidth: 0,
  },
  rowBetweenMB25W100p: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
    width: '100%',
  },
  maxH400_w100p: {
    maxHeight: 400,
    width: '100%',
  },
  maxH300_w100p: {
    maxHeight: 300,
    width: '100%',
  },
});

export const ManagementStyles = StyleSheet.create({
  container: {
    paddingHorizontal: 25,
    paddingTop: 10,
    paddingBottom: 10,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 13,
    color: '#555',
  },
  btnBlue: {
    backgroundColor: '#2D5DD1',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  btnBlueText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 13,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 45,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    color: '#333',
  },
  tableContainer: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    marginHorizontal: 20,
  },
  tableHeaderPrimary: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    paddingVertical: 14,
  },
  tableHeaderMaron: {
    flexDirection: 'row',
    backgroundColor: '#801919',
    paddingVertical: 14,
  },
  thText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 13,
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#EBEBEB',
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  tdText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
  },
  tdTextSmall: {
    fontSize: 12,
    color: '#555',
    textAlign: 'center',
  },
  roleBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  roleBadgeText: {
    fontSize: 10,
    fontWeight: '900',
  },
  actionCell: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  colCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  paddingH6: {
    paddingHorizontal: 6,
  },
  ph15: {
    paddingHorizontal: 15,
  },
  flex05: {
    flex: 0.5,
  },
  flex08: {
    flex: 0.8,
  },
  flex12: {
    flex: 1.2,
  },
  flex2: {
    flex: 2,
  },
  thText14: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
  },
  thTextLeft14: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'left',
  },
  tdNo: {
    fontSize: 14,
    color: '#000',
    fontWeight: '500',
    textAlign: 'center',
  },
  badgeLayanan: {
    alignSelf: 'flex-start',
    backgroundColor: '#EADCDA',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#C8A2A0',
  },
  badgeLayananText: {
    color: '#801919',
    fontSize: 12,
    fontWeight: 'bold',
  },
  tdNamaTindakan: {
    fontSize: 13,
    color: '#000',
    fontWeight: 'bold',
  },
  emptyStateContainer: {
    padding: 30,
    alignItems: 'center',
  },
  emptyStateText: {
    color: '#888',
    fontSize: 14,
  },
  flex04: {
    flex: 0.4,
  },
  flex07: {
    flex: 0.7,
  },
  flex1: {
    flex: 1,
  },
  badgeAdmin: {
    backgroundColor: '#E3F2FD',
  },
  badgeAdminText: {
    color: '#1976D2',
  },
  badgeDokter: {
    backgroundColor: '#E8F5E9',
  },
  badgeDokterText: {
    color: '#2E7D32',
  },
  tdEmail: {
    color: '#444',
  },
  emptyUsersContainer: {
    width: '100%',
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flex15: {
    flex: 1.5,
  },
  badgeLK: {
    backgroundColor: '#D6E0E9',
  },
  badgeLKText: {
    color: '#194580',
  },
  badgePR: {
    backgroundColor: '#E9D6D6',
  },
  badgePRText: {
    color: '#801919',
  },
  tdTextLeft: {
    textAlign: 'left',
  },
  emptyPasienContainer: {
    width: '100%',
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export const GlobalStyles = StyleSheet.create({
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: Colors.black,
    textAlign: 'center',
  },
  label: {
    fontSize: 14,
    color: Colors.text,
    fontWeight: '500',
  },
  headerContainer: {
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  headerTitle: {
    color: Colors.white,
    fontSize: 22,
    fontWeight: 'bold',
    marginLeft: 15,
  },
  headerRightText: {
    color: Colors.white,
    fontSize: 16,
  },
  topBarContainer: {
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  topBarLogoBadge: {
    backgroundColor: Colors.white,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  topBarTextRight: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: '600',
  },
  topBarTextRightBold: {
    color: Colors.white,
    fontSize: 14,
    marginBottom: 0,
    fontWeight: 'bold',
  },
  topBarRightContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  topBarRightTextWrapper: {
    alignItems: 'flex-end',
    flexShrink: 1,
  },
  logoutButtonBackground: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    padding: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  alignEnd: {
    alignItems: 'flex-end',
  },
  inputWrapper: {
    marginBottom: 20,
    width: '100%',
  },
  inputLabel: {
    fontSize: 14,
    color: Colors.text,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  inputLabelSmall: {
    fontSize: 13,
    color: '#666',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 25,
    height: 50,
    backgroundColor: Colors.formInputBg,
    paddingHorizontal: 15,
  },
  inputText: {
    flex: 1,
    color: Colors.black,
    fontSize: 16,
  },
  inputIcon: {
    marginRight: 10,
  },
  inputRightIcon: {
    marginLeft: 10,
  },
  pickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F2E3E3',
    borderWidth: 1.5,
    borderColor: Colors.black,
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 55,
  },
  pickerText: {
    fontSize: 16,
    color: Colors.black,
    includeFontPadding: false,
    lineHeight: 22,
  },
  pickerPlaceholder: {
    color: Colors.placeholder,
  },
  selectionModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectionModalContent: {
    width: '85%',
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 25,
    maxHeight: '70%',
    borderWidth: 2,
    borderColor: Colors.black,
  },
  selectionModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    paddingBottom: 15,
  },
  selectionModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  selectionOptionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: '#EEEEEE',
  },
  selectionOptionItemActive: {
    backgroundColor: '#F9F9F9',
  },
  selectionOptionText: {
    fontSize: 16,
    color: '#333',
    includeFontPadding: false,
    lineHeight: 22,
  },
  selectionOptionTextActive: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  pillInput: {
    borderWidth: 2,
    borderColor: Colors.black,
    borderRadius: 25,
    height: 50,
    backgroundColor: Colors.white,
    color: Colors.black,
    fontSize: 16,
    paddingHorizontal: 20,
  },
  formInput: {
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 25,
    height: 50,
    backgroundColor: Colors.formInputBg,
    color: Colors.black,
    fontSize: 16,
    paddingHorizontal: 20,
  },
  primaryButton: {
    backgroundColor: Colors.primary,
    borderRadius: 25,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  dashboardCard: {
    backgroundColor: Colors.secondary,
    borderWidth: 1.2,
    borderColor: Colors.cardBorder,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  dashboardCardText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 10,
    textAlign: 'center',
  },
  dashboardCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  docHeader: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold' as any,
    fontSize: 22,
    textAlign: 'center',
    color: Colors.black,
  },
  docTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold' as any,
    fontSize: 18,
    textAlign: 'center',
    color: Colors.black,
    marginVertical: 10,
  },
  docBodySerif: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontSize: 14,
    color: Colors.black,
  },
  docBodyCursive: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontStyle: 'italic',
    fontSize: 14,
    fontWeight: '600' as any,
    color: Colors.black,
  },
  bottomNavContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    height: 70,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    elevation: 8,
  },
  bottomNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  bottomNavText: {
    color: Colors.white,
    fontSize: 11,
    marginTop: 4,
    opacity: 0.8,
  },
  bottomNavActiveText: {
    opacity: 1,
    fontWeight: 'bold',
  },
  formCard: {
    backgroundColor: Colors.white,
    marginHorizontal: 20,
    borderRadius: 25,
    padding: 30,
    borderWidth: 2,
    borderColor: Colors.black,
    elevation: 3,
  },
  formSectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#333',
    marginBottom: 8,
    letterSpacing: 1.2,
  },

  formDivider: {
    height: 1,
    backgroundColor: Colors.black,
    marginBottom: 20,
    opacity: 0.3,
  },
  btnBatal: {
    backgroundColor: '#B3AFAF',
    width: 140,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  btnBatalText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  btnSimpan: {
    backgroundColor: '#2E50D4',
    width: 140,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  btnActionUpdate: {
    backgroundColor: '#EBC112',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnBlueInfo: {
    backgroundColor: '#1E88E5',
  },
  btnActionDelete: {
    backgroundColor: Colors.primary,
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  badgeContainer: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  badgeText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.white,
  },
  genderPR: {
    backgroundColor: '#FF69B4',
  },
  genderLK: {
    backgroundColor: '#4169E1',
  },
  userCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    marginBottom: 12,
    borderLeftWidth: 5,
    borderLeftColor: Colors.black,
    backgroundColor: Colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EEEEEE',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#E0E0E0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  avatarText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.black,
  },
  userName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.text,
  },
  userRole: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: 20,
    width: '100%',
  },
  detailItem: {
    flex: 1,
    paddingRight: 10,
  },
  detailLabel: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.black,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: 16,
    color: '#666',
    fontStyle: 'italic',
    lineHeight: 22,
  },
  detailFooter: {
    marginTop: 20,
    alignItems: 'flex-end',
  },
  btnBack: {
    backgroundColor: '#2E50D4',
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 20,
  },
  btnBackText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 15,
  },
  listTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
  },
  listSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 15,
    paddingHorizontal: 15,
    borderWidth: 2,
    borderColor: Colors.black,
    height: 60,
    flex: 1,
  },
  listSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  listAddButton: {
    backgroundColor: '#2E50D4',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    height: 60,
    borderRadius: 12,
    justifyContent: 'center',
  },
  listAddButtonText: {
    color: 'white',
    fontWeight: 'bold',
    marginLeft: 5,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 5,
  },
  searchWrapper: {
    flex: 1,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  listAddButtonContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  listLeftSpacer: {
    width: 0,
    display: 'none',
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  emptyContent: {
    alignItems: 'center',
    marginTop: 50,
  },
  emptyText: {
    color: '#888',
    fontSize: 16,
  },
  cardActions: {
    flexDirection: 'row',
  },
  cardActionBtn: {
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalBox: {
    width: 310,
    maxWidth: '90%',
    backgroundColor: Colors.white,
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 25,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Colors.primary,
  },
  modalText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.black,
    textAlign: 'center',
    marginBottom: 20,
  },
  modalActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  btnModalBatal: {
    backgroundColor: '#B3AFAF',
    flex: 1,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  btnModalHapus: {
    backgroundColor: Colors.primary,
    flex: 1,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  btnModalText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  tableContainer: {
    flex: 1,
    marginBottom: 20,
  },
  tableContentWrapper: {
    backgroundColor: Colors.white,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderWidth: 2,
    borderColor: Colors.black,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    borderBottomWidth: 2,
    borderBottomColor: Colors.black,
    width: '100%',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: Colors.black,
    width: '100%',
  },
  tableRowLast: {
    borderBottomWidth: 2,
  },
  tableHeaderCell: {
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
    borderRightColor: Colors.black,
  },
  tableCell: {
    paddingVertical: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 2,
    borderRightColor: Colors.black,
  },
  tableCellNo: {
    width: 50,
  },
  tableCellName: {
    flex: 1,
    paddingHorizontal: 12,
    alignItems: 'flex-start',
  },
  tableCellRole: {
    width: 100,
  },
  tableCellSpec: {
    width: 130,
  },
  tableCellTglLahir: {
    width: 110,
  },
  tableCellJK: {
    width: 110,
  },
  tableCellAlamat: {
    width: 200,
  },
  tableCellPekerjaan: {
    width: 120,
  },
  tableCellNope: {
    width: 120,
  },
  tableCellAlergi: {
    width: 120,
  },
  tableCellDokter: {
    width: 150,
  },


  detailMainCard: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 50,
    padding: 40,
    marginTop: 30,
    marginHorizontal: 35,

    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 10,
  },


  tableCardAtomic: {
    width: '100%',
    maxWidth: 900,
    backgroundColor: Colors.white,
    borderRadius: 0,
    overflow: 'hidden',
  },
  filterSectionAtomic: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: Colors.white,
  },
  pickerWrapper: {
    flex: 1,
    minWidth: 200,
    height: 50,
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: Colors.black,
    borderRadius: 10,
    backgroundColor: Colors.white,
    paddingHorizontal: 5,
    marginLeft: 10,
  },
  picker: {
    width: '100%',
    height: 50,
    color: Colors.black,
  },
  tableHeaderAtomic: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    alignItems: 'stretch',
    borderTopWidth: 1,
    borderTopColor: Colors.black,
  },
  tableBodyWrapperAtomic: {
    minHeight: 150,
  },
  tableRowAtomic: {
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 65,
  },
  tableCellAtomic: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    borderRightWidth: 1,
    borderRightColor: Colors.black,
    borderBottomWidth: 1,
    borderBottomColor: Colors.black,
  },
  tableThText: {
    fontWeight: 'bold',
    fontSize: 13,
    color: Colors.black,
    textAlign: 'center',
  },
  tableTdText: {
    fontSize: 12,
    color: Colors.black,
    textAlign: 'center',
  },
  tableFooterRow: {
    flexDirection: 'row',
    height: 55,
  },
  tableCellFirst: {
    borderLeftWidth: 1,
    borderLeftColor: Colors.black,
  },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  exportBtnText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  detailCard: {
    width: '100%',
    maxWidth: 900,
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.black,
    borderRadius: 25,
    padding: 30,
    marginBottom: 30,
  },


  btnKembaliLink: {
    backgroundColor: '#2D58D1',
    paddingVertical: 15,
    paddingHorizontal: 50,
    borderRadius: 35,
  },
  btnKembaliText: {
    color: Colors.white,
    fontWeight: 'bold',
    fontSize: 16,
    textTransform: 'none',
  },
  tableCellAction: {
    width: 140,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRightWidth: 0,
  },
  tableHeaderText: {
    fontWeight: 'bold',
    fontSize: 15,
    color: Colors.black,
  },
  tableRowText: {
    fontSize: 14,
    color: Colors.black,
  },
  captchaSection: {
    marginTop: 10,
    marginBottom: 35,
  },
  captchaBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#888888',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  captchaText: {
    marginLeft: 10,
    fontSize: 14,
    color: '#333333',
  },
  captchaHint: {
    fontSize: 10,
    color: Colors.primary,
    marginTop: 8,
    fontStyle: 'italic',
    marginLeft: 4,
  },
  captchaMathBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  captchaMathQuestion: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 8,
    overflow: 'hidden' as any,
    borderWidth: 1,
    borderColor: '#DDDDDD'
  },
  captchaMathInput: {
    borderWidth: 1,
    borderColor: '#888888',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 8,
    fontSize: 16,
    width: 100,
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    color: '#333333'
  },
  cardWrapper: {
    backgroundColor: Colors.cardRed,
    borderRadius: 15,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#984B4B',
  },
  cardVertical: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardHorizontal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardText: {
    color: Colors.white,
    fontWeight: 'bold',
    marginTop: 10,
    textAlign: 'center',
  },
  cardTextHorizontal: {
    marginLeft: 15,
    marginTop: 0,
  },
  infoCardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
  },
  infoCardIconContainer: {
    width: 45,
    height: 45,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  infoCardTextContainer: {
    flex: 1,
  },
  infoCardLabel: {
    fontSize: 12,
    color: '#888',
    marginBottom: 2,
  },
  infoCardValue: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  baseCardBody: {
    borderRadius: 15,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#EEE',
  },


  historyFilterCard: {
    marginHorizontal: 10,
    marginVertical: 10,
    backgroundColor: Colors.white,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    padding: 10,
    elevation: 3,
  },
  historyFilterRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  historyFilterItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  historyFilterLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
    width: 80,
  },
  historyPickerBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    height: 40,
  },
  historyTableContainer: {
    marginHorizontal: 10,
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.black,
    borderRadius: 0,
    overflow: 'hidden',
  },
  historyTableRowAlt: {
    backgroundColor: '#F9F9F9',
  },
  historyFooterCount: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#F5F5F5',
    borderTopWidth: 1,
    borderTopColor: '#DDD',
  },
  historyFooterText: {
    fontSize: 12,
    color: Colors.text,
  },
  historyResetText: {
    fontSize: 12,
    color: Colors.primary,
    fontWeight: 'bold',
  },
  historyFilterCardPremium: {
    borderRadius: 8,
    paddingVertical: 25,
    paddingHorizontal: 50,
    borderColor: '#801919',
    borderWidth: 0.8,
    marginHorizontal: 20,
    marginTop: 15,
    backgroundColor: Colors.white,
  },
  historyFilterColumnLeft: {
    width: 280,
    flexDirection: 'row',
    alignItems: 'center',
  },
  historyFilterColumnRight: {
    width: 320,
    flexDirection: 'row',
    alignItems: 'center',
  },
  historyFilterLabelBold: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333',
  },
  historyDropdownButton: {
    backgroundColor: 'white',
    borderColor: 'black',
    borderWidth: 1.5,
    borderRadius: 10,
    height: 38,
    paddingHorizontal: 12,
  },
  historyExportBtnContainer: {
    marginTop: 15,
    alignSelf: 'flex-end',
    marginRight: 20,
    backgroundColor: '#345AD9',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  historyTableContainerPremium: {
    marginHorizontal: 20,
    borderRadius: 12,
    borderColor: '#801919',
    borderWidth: 1.2,
    overflow: 'hidden',
    marginTop: 15,
    elevation: 5,
    shadowColor: '#801919',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    backgroundColor: 'white',
  },
  historyTableHeaderMaron: {
    backgroundColor: '#801919',
    height: 45,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  historyTableCellTgl: { width: 100 },
  historyTableCellNama: { width: 140 },
  historyTableCellDokter: { width: 140 },
  historyTableCellLayanan: { width: 100 },
  historyTableCellGigi: { width: 80 },
  historyTableCellDiagnosa: { width: 200 },
  historyTableCellPerawatan: { width: 180 },
  historyTableCellKeterangan: { width: 220 },
  historyHeaderCellBorder: { borderRightColor: '#601010' },
  historyBodyCellBorder: { borderRightColor: '#aaa' },
  historyContainer: {
    paddingBottom: 40,
    flex: 1,
  },
  historyFilterLabelWrapperLeft: {
    width: 95,
  },
  historyFilterLabelWrapperRight: {
    width: 90,
  },
  historyExportWrapper: {
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 5,
  },
  logoCircleSmall: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },

  dropdownSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#DDD'
  },
  dropdownSearchInput: {
    flex: 1,
    minHeight: 40,
    marginLeft: 5,
    color: '#333',
    paddingVertical: 5,
  },
  modalScrollViewContent: {
    maxHeight: 300,
    width: '100%',
  },
  alignCenter: {
    alignItems: 'center',
  },
  mb0: {
    marginBottom: 0,
  },
  disabledInput: {
    opacity: 0.5,
    backgroundColor: '#EEE',
  },
  justifyCenter: {
    justifyContent: 'center',
  },
  pb40: {
    paddingBottom: 40,
  },
  textAlignLeft: {
    textAlign: 'left',
  },
  textAlignCenter: {
    textAlign: 'center',
  },
  pl10: {
    paddingLeft: 10,
  },
  mv30: {
    marginVertical: 30,
  },
  p30: {
    padding: 30,
  },
  textLightGray: {
    color: '#999',
  },
  textLightGray2: {
    color: '#A0A0A0',
  },
  mb12: {
    marginBottom: 12,
  },
  mb15: {
    marginBottom: 15,
  },
  maxH400: {
    maxHeight: 400,
  },
  inputBlack: {
    color: '#000',
  },
  inputGray: {
    backgroundColor: '#F8F8F8',
  },
  textAreaSmall: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: 15,
  },
  justifyEnd: {
    justifyContent: 'flex-end',
  },
  gap15: {
    gap: 15,
  },
  btnGray: {
    backgroundColor: '#B3AFAF',
  },
  fontSerif: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
  },
  fontSize14: {
    fontSize: 14,
  },
  fontSize16: {
    fontSize: 16,
  },
  textJustify: {
    textAlign: 'justify',
  },
  lineHeight22: {
    lineHeight: 22,
  },
  logoCircleLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1.5,
    borderColor: '#C62828',
  },
  w90p: {
    width: '90%',
  },
  opacity07: {
    opacity: 0.7,
  },
  opacity1: {
    opacity: 1,
  },
  flexRowAlignCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  maxW250: {
    maxWidth: 250,
  },
  h45: {
    height: 45,
  },
  ph20: {
    paddingHorizontal: 20,
  },


  billCard: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    padding: 20,
    marginBottom: 20,
    flexDirection: 'row',
    elevation: 3,
  },
  billBody: {
    flex: 1,
  },
  billInfoRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  billLabel: {
    width: 125,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  billColon: {
    width: 15,
    fontSize: 14,
    fontWeight: 'bold',
  },
  billValue: {
    flex: 1,
    fontSize: 14,
    color: '#555',
  },
  billActionSection: {
    justifyContent: 'center',
    marginLeft: 15,
  },
  billCetakBtn: {
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: 135,
  },
  billCetakBtnText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 5,
  },
  billDateBox: {
    borderWidth: 1,
    borderColor: '#CCC',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Colors.white,
    marginTop: 2,
  },
  billDateText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  statusPill: {
    paddingVertical: 6,
    paddingHorizontal: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  statusPillText: {
    fontWeight: 'bold',
    fontSize: 13,
  },
  rujukanCard: {
    backgroundColor: Colors.white,
    padding: 15,
    borderRadius: 15,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  rujukanCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  rujukanCardSubtitle: {
    fontSize: 13,
    color: '#666',
  },
  rujukanActionBtn: {
    backgroundColor: Colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  rujukanActionBtnText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 5,
  },
  mt8: {
    marginTop: 8,
  },
  captchaQuestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  captchaRefreshIcon: {
    color: '#007BFF',
    fontSize: 20,
    marginLeft: 10,
  },


  receiptContainer: {
    width: '95%',
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.black,
    elevation: 3,
  },
  rujukanContainer: {
    paddingTop: 38,
    paddingBottom: 76,
    paddingHorizontal: 113,
  },
  kwitansiContainer: {
    paddingTop: 19,
    paddingBottom: 38,
    paddingHorizontal: 57,
  },
  receiptHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  receiptLogoAligner: {
    width: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  receiptHeaderTextContainer: {
    flex: 1,
    alignItems: 'center',
  },
  receiptTitleUmum: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    color: Colors.black,
    textAlign: 'center',
  },
  receiptDoctorName: {
    fontSize: 16,
    fontWeight: '900',
    color: Colors.black,
    textAlign: 'center',
    marginVertical: 1,
  },
  receiptSipText: {
    fontSize: 11,
    color: Colors.black,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 1,
  },
  receiptAddressText: {
    fontSize: 11,
    color: Colors.black,
    textAlign: 'center',
  },
  receiptLineThick: {
    height: 3,
    backgroundColor: Colors.black,
    marginBottom: 2,
  },
  receiptLineThin: {
    height: 1,
    backgroundColor: Colors.black,
  },
  receiptTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    color: Colors.black,
    textAlign: 'center',
  },
  receiptNo: {
    fontSize: 18,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    textAlign: 'center',
    marginTop: 2,
  },
  receiptInfoRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  receiptSubInfoRow: {
    flexDirection: 'row',
    marginBottom: 10,
    marginLeft: 40,
  },
  receiptLabel: {
    width: 150,
    fontSize: 15,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontStyle: 'italic',
    fontWeight: 'bold',
    color: Colors.black,
  },
  receiptSubLabel: {
    width: 110,
    fontSize: 15,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontStyle: 'italic',
    fontWeight: 'bold',
    color: Colors.black,
  },
  receiptColon: {
    width: 25,
    fontSize: 15,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold',
    color: Colors.black,
    textAlign: 'center',
  },
  receiptValue: {
    flex: 1,
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    color: Colors.black,
  },
  receiptNominalBoxWrapper: {
    width: '45%',
  },
  receiptNominalText: {
    fontSize: 16,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold',
    fontStyle: 'italic',
    color: Colors.black,
    marginLeft: 5,
    marginVertical: 2,
  },
  receiptAdminSign: {
    alignItems: 'flex-end',
    width: '45%',
  },
  receiptDateInfo: {
    textAlign: 'right',
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    color: Colors.black,
  },
  receiptLogoCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
    height: 80,
    borderRadius: 40,
    overflow: 'hidden',
  },
  receiptDoubleLineContainer: {
    marginTop: 10,
    marginBottom: 5,
  },
  receiptDoubleLineSmall: {
    marginVertical: 4,
  },
  receiptSignSpace: {
    height: 60,
  },
  receiptFooter: {
    marginTop: 10,
  },
  receiptNominalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 20,
  },


  rujukanTitleUmumHuge: {
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    color: Colors.black,
    textAlign: 'center',
    marginBottom: 4,
  },
  rujukanBoldText: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold',
    fontSize: 14,
    color: Colors.black,
  },
  rujukanDotLineUnder: {
    borderBottomWidth: 1,
    borderBottomColor: '#aaa',
    alignSelf: 'flex-start',
    minWidth: 200,
    marginBottom: 5,
  },
  rujukanValueRowWrapper: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  rujukanGenderTextRight: {
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 10,
  },
  rujukanDateInfoBold: {
    textAlign: 'center',
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    fontWeight: 'bold',
    color: Colors.black,
    marginTop: 2,
  },
  rujukanAdminSign: {
    alignItems: 'center',
    width: 250,
  },
  rujukanLogo: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    borderWidth: 2,
    borderColor: '#C62828',
    marginRight: 15,
  },
  doctorNameSmall: {
    fontSize: 13,
    letterSpacing: 1,
  },
});

export const AdminDashboardStyles = StyleSheet.create({
  mainContainer: {
    flexDirection: 'row',
    padding: 25,
    backgroundColor: '#EAEAEA',
  },
  leftColumn: {
    flex: 1,
    maxWidth: 380,
    borderColor: Colors.primary,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 15,
    marginRight: 20,
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  menuSectionTitle: {
    textAlign: 'center',
    fontWeight: '900',
    fontSize: 13,
    color: '#555',
    letterSpacing: 0.5,
  },
  menuSectionTitleTop: {
    marginBottom: 20,
  },
  menuSectionTitleBottom: {
    marginTop: 15,
    marginBottom: 20,
  },
  menuGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
  },
  userInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#D4D4D4',
    paddingTop: 15,
    marginTop: 20,
    paddingHorizontal: 10,
  },
  userRoleText: {
    fontWeight: 'bold',
    fontSize: 11,
    color: Colors.primary,
    marginBottom: 2,
  },
  userNameText: {
    fontSize: 9,
    color: '#888',
    fontWeight: '600',
  },
  logoutButton: {
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 30,
    alignItems: 'center',
    elevation: 3,
  },
  logoutButtonText: {
    color: 'white',
    fontWeight: 'bold',
    marginRight: 8,
    fontSize: 13,
  },
  rightColumn: {
    flex: 2,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    paddingVertical: 18,
    paddingHorizontal: 25,
  },
  thName: {
    flex: 2,
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  thCenter: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 15,
  },
  flex1_5: {
    flex: 1.5,
  },
  flex2: {
    flex: 2,
  },
  emptyStateText: {
    textAlign: 'center',
    marginTop: 50,
    color: '#888',
    fontStyle: 'italic',
    fontSize: 15,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 18,
    paddingHorizontal: 25,
    borderBottomWidth: 1,
    borderColor: '#EBEBEB',
    alignItems: 'center',
  },
  tableRowEven: {
    backgroundColor: '#FFFFFF',
  },
  tableRowOdd: {
    backgroundColor: '#FAFAFA',
  },
  tdName: {
    flex: 2,
    fontWeight: 'bold',
    color: '#222',
    fontSize: 14,
  },
  tdCenterContainer: {
    flex: 1.5,
    alignItems: 'center',
  },
  badgeContainer: {
    backgroundColor: '#E9D6D6',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  badgeText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  tdLayanan: {
    flex: 2,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#333',
    fontSize: 14,
  },
  menuIconTouchable: {
    alignItems: 'center',
    marginHorizontal: 5,
    marginBottom: 20,
    width: 65,
  },
  menuIconOuterBox: {
    width: 62,
    height: 62,
    borderRadius: 14,
    borderWidth: 1.2,
    borderColor: Colors.primary,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  menuIconInnerBox: {
    width: 48,
    height: 48,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIconText: {
    fontSize: 9,
    color: Colors.primary,
    textAlign: 'center',
    marginTop: 6,
    fontWeight: 'bold',
    lineHeight: 12,
  },
  rightColumnWrapper: {
    flex: 2,
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  dateTimeItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateTimeLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    color: Colors.primary,
  },
  dateTimeValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#333',
  },
});

export const DentalRecordStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  topSection: {
    paddingHorizontal: 25,
    paddingTop: 20,
    backgroundColor: '#F5F5F5',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#000',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#333',
  },
  btnRecordBaru: {
    backgroundColor: '#3B82F6',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  btnRecordBaruText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 5,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#CCC',
    borderRadius: 12,
    height: 55,
    paddingHorizontal: 15,
    marginBottom: 25,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    marginLeft: 10,
  },
  tableWrapper: {
    marginHorizontal: 25,
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 12,
    backgroundColor: '#FFF',
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    marginBottom: 30,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  thText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
  thCenter: {
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: '#EBEBEB',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  tdText: {
    fontWeight: 'bold',
    color: '#222',
    fontSize: 14,
  },
  tdCenterText: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#222',
    fontSize: 14,
  },
  badgeContainerOuter: {
    alignItems: 'center',
  },
  badgeContainer: {
    backgroundColor: '#E9D6D6',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  badgeText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  btnEditAction: {
    backgroundColor: '#FDD835',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    elevation: 1,
  },
  modalContentPremium: {
    borderColor: Colors.primary,
    borderWidth: 2,
    borderRadius: 30,
    padding: 25,
    backgroundColor: 'white',
  },
  modalTitleLeft: {
    marginBottom: 0,
    color: Colors.primary,
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'left',
  },
  modalCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnEditActionText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 13,
    marginLeft: 5,
  },
  colNama: { flex: 2 },
  colGender: { flex: 1.2 },
  colKeluhan: { flex: 2.5 },
  colLayanan: { flex: 1.8 },
  colStatus: { flex: 1.5 },
  colAksi: { flex: 0.8 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    width: 320,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: Colors.primary,
    paddingVertical: 35,
    paddingHorizontal: 30,
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#7a1b1b',
    shadowOffset: { width: -2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 1,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: Colors.primary,
    marginBottom: 30,
    textAlign: 'center',
  },
  modalOptionBtn: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    backgroundColor: '#FFFFFF',
    marginBottom: 15,
    alignItems: 'center',
  },
  modalOptionText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export const CreateRecordStyles = StyleSheet.create({
  mainContainer: {
    flexGrow: 1,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 25,
    paddingTop: 20,
    paddingBottom: 40,
  },
  card: {
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 15,
    padding: 30,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#555',
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  divider: {
    height: 1.5,
    backgroundColor: '#D0D0D0',
    marginBottom: 25,
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 10,
  },
  inputDropdown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1.5,
    borderColor: Colors.primary,
    borderRadius: 16,
    paddingHorizontal: 20,
    height: 60,
    marginBottom: 15,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  inputText: {
    fontSize: 15,
    color: '#555',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 5,
    marginBottom: 30,
  },
  checkboxWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '12%',
    marginBottom: 15,
  },
  // Khusus untuk 16 per baris
  checkboxWrapper16: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '6.2%',
    marginBottom: 10,
    justifyContent: 'center',
  },
  checkbox: {
    width: 16,
    height: 16,
    borderWidth: 1.2,
    borderColor: Colors.primary,
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: Colors.primary,
  },
  checkboxLabel: {
    fontSize: 10,
    color: '#555',
    fontWeight: 'bold',
    marginTop: 2,
  },
  textArea: {
    backgroundColor: '#FFF',
    borderWidth: 1.5,
    borderColor: Colors.primary,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 15,
    height: 120,
    textAlignVertical: 'top',
    fontSize: 15,
    color: '#555',
    marginBottom: 25,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  btnSimpanContainer: {
    alignItems: 'flex-end',
    marginTop: 10,
  },
  btnSimpan: {
    backgroundColor: '#3B82F6',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 30,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  btnSimpanText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export const DoctorDashboardStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  doctorInfoContainer: {
    paddingHorizontal: 30,
    paddingTop: 15,
    marginBottom: 20,
  },
  doctorName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
  },
  doctorSpec: {
    fontSize: 12,
    fontWeight: 'bold',
    color: Colors.primary,
    marginTop: 2,
  },
  currentDate: {
    fontSize: 14,
    color: Colors.primary,
    marginTop: 10,
    fontWeight: '500',
  },
  tableWrapper: {
    marginHorizontal: 25,
    borderWidth: 1.5,
    borderColor: '#C0C0C0',
    borderRadius: 12,
    backgroundColor: '#FFF',
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    paddingVertical: 15,
    paddingHorizontal: 15,
  },
  thText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: '#EBEBEB',
    alignItems: 'center',
  },
  tdText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '600',
    textAlign: 'center',
  },
  badgeContainer: {
    backgroundColor: '#E9D6D6',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'center',
  },
  badgeText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  btnEdit: {
    backgroundColor: '#FDD835',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignSelf: 'center',
  },
  btnEditText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 13,
    marginLeft: 4,
  },
  colName: { flex: 2 },
  colGender: { flex: 1.5 },
  colKeluhan: { flex: 3 },
  colAksi: { flex: 1 },
  btnBlueInfo: {
    backgroundColor: '#1E88E5',
  },
});

export const PatientTableStyles = StyleSheet.create({
  headerContainer: {
    paddingHorizontal: 25,
    paddingTop: 20,
    backgroundColor: '#F5F5F5',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#000',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#333',
    marginTop: 2,
  },
  btnNewPatient: {
    backgroundColor: '#3B82F6', // Match + Record Baru
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    elevation: 2,
  },
  btnNewPatientText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 5,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#CCC',
    borderRadius: 12,
    height: 55,
    paddingHorizontal: 15,
    marginBottom: 25,
    marginTop: 0,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    marginLeft: 10,
  },
  tableWrapper: {
    marginHorizontal: 25,
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 12,
    backgroundColor: '#FFF',
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    marginBottom: 30,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
  },
  thCell: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  thText: {
    color: '#FFF',
    fontWeight: '900',
    fontSize: 15,
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: '#EBEBEB',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  tdCell: {
    paddingVertical: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#EBEBEB',
  },
  tableBody: {
    backgroundColor: '#FFF',
  },
  tdText: {
    fontWeight: 'bold',
    color: '#222',
    fontSize: 14,
  },
  badgeContainer: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E9D6D6',
    maxWidth: 60,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '900',
    marginRight: 2,
  },
  badgePR: {
    backgroundColor: '#E9D6D6',
    color: '#801919',
  },
  badgeLK: {
    backgroundColor: '#D6E0E9',
    color: '#194580',
  },
  actionBtn: {
    marginHorizontal: 5,
  },
  // Columns
  colNama: { flex: 1.5, paddingHorizontal: 15, borderColor: '#EBEBEB' },
  colTgl: { flex: 1.2, alignItems: 'center', borderColor: '#EBEBEB' },
  colGender: { flex: 0.8, alignItems: 'center', borderColor: '#EBEBEB' },
  colAlamat: { flex: 1.5, paddingHorizontal: 15, borderColor: '#EBEBEB' },
  colPekerjaan: { flex: 1.2, paddingHorizontal: 15, borderColor: '#EBEBEB' },
  colNope: { flex: 1.3, alignItems: 'center', borderColor: '#EBEBEB' },
  colAlergi: { flex: 1, paddingHorizontal: 15, borderColor: '#EBEBEB' },
  colAksi: { flex: 1.2, flexDirection: 'row', justifyContent: 'center' },
});

export const PatientFormStyles = StyleSheet.create({
  mainContainer: {
    flexGrow: 1,
    backgroundColor: '#FCFCFC',
    paddingHorizontal: 60,
    paddingTop: 40,
    paddingBottom: 60,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    borderWidth: 1.2,
    borderColor: '#801919',
    padding: 30,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  divider: {
    height: 1,
    backgroundColor: '#DDDDDD',
    marginBottom: 25,
  },
  fieldLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.2,
    borderColor: '#C0C0C0',
    borderRadius: 12,
    height: 50,
    paddingHorizontal: 15,
    fontSize: 15,
    color: '#333',
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 0,
  },
  col: {
    width: '48%',
  },
  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 25,
  },
  btnSimpan: {
    backgroundColor: '#3B59DA',
    paddingVertical: 12,
    paddingHorizontal: 40,
    borderRadius: 25,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  btnSimpanText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 15,
  },
});

export const PatientDetailStyles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#FCFCFC',
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#DDDDDD',
    marginBottom: 25,
    elevation: 2,
  },
  infoTitleBar: {
    backgroundColor: Colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 15,
  },
  infoTitleText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  gridRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#EEEEEE',
  },
  gridCell: {
    flex: 1,
    padding: 15,
    borderRightWidth: 1,
    borderColor: '#EEEEEE',
    minHeight: 80,
  },
  gridCellLast: {
    borderRightWidth: 0,
  },
  infoLabel: {
    fontSize: 13,
    color: '#666666',
    fontWeight: '500',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 15,
    color: '#000000',
    fontWeight: 'bold',
  },
  genderPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 20,
    paddingVertical: 6,
    borderRadius: 10,
    marginTop: 5,
  },
  genderPillPR: {
    backgroundColor: '#E9D6D6',
  },
  genderPillLK: {
    backgroundColor: '#D6E0E9',
  },
  genderPillText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  textMaron: {
    color: '#801919',
  },
  textNavy: {
    color: '#194580',
  },
  historyTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    marginTop: 10,
  },
  historySectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
    textTransform: 'uppercase',
  },
  filterAndExport: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropdownWrapper: {
    width: 130,
    marginRight: 10,
  },
  dropdownButton: {
    height: 35,
    backgroundColor: '#E9D6D6',
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 0,
  },
  btnExport: {
    backgroundColor: Colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  btnExportText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
});

export const DoctorStyles = StyleSheet.create({
  treatmentSelectionContainer: {
    marginBottom: 10,
  },
  treatmentItem: {
    marginRight: 15,
    marginBottom: 12,
  },
  treatmentBadge: {
    backgroundColor: '#F9F9F9',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EEE',
  },
  treatmentBadgeChecked: {
    backgroundColor: '#FFF0F0',
    borderColor: Colors.primary,
  },
  checkboxInner: {
    marginRight: 8,
  },
  checkboxCheckedText: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  checkboxUncheckedText: {
    color: '#444',
    fontWeight: 'normal',
  },
});

export const AlertStyles = StyleSheet.create({
  icon: {
    marginBottom: 15,
  },
  message: {
    fontWeight: 'normal',
    fontSize: 14,
    marginTop: -10,
    marginBottom: 25,
  },
  btnConfirm: {
    borderRadius: 15,
  },
  btnWithMargin: {
    marginLeft: 10,
  },
});
